import { TOKENS_SYMBOLS } from "./tokens";
import {
  Furucombo,
  Uniswapv2,
  Aave,
  Sushiswap,
  Curve,
  Yearn,
  Compound,
  Maker,
  // OneInch,
  // Paraswap,
  // UniswapV3,
  Bprotocol,
  Synthetix,
  Utility,
} from "./furucomboConfig";

const TOKENS = TOKENS_SYMBOLS;

export const PAIR_LIST = [
  {
    token: TOKENS.WETH,
    collateral: TOKENS.USDC,
    tokenPrice: 1121.08,
    liquidation: 0.750756387059963,
    health: 0.117984,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 5882,
    available: 7855,
  },
  {
    token: TOKENS.DAI,
    collateral: TOKENS.WETH,
    tokenPrice: 1,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 2437,
    available: 292450,
  },
  {
    token: TOKENS.DAI,
    collateral: TOKENS.USDC,
    tokenPrice: 1,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 0.001008,
  },
];

export const BORROW_PAIR_LIST = [
  {
    token: TOKENS.USDC,
    tokenLogo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    collateral: TOKENS.ETH,
    collateralLogo:
      "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    collateralPrice: 1531.83,
    tokenPrice: 1,
    apr: 0.25,
    ltv: 75,
    oracle: "Chainlink",
    strategy: "Active",
    borrowed: 5777,
    available: 1728,
  },
  {
    token: TOKENS.USDC,
    tokenLogo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    collateral: TOKENS.BNB,
    collateralLogo:
      "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    collateralPrice: 262.09,
    tokenPrice: 1,
    apr: 1,
    ltv: 75,
    oracle: "Chainlink",
    borrowed: 0,
    available: 0,
  },
  {
    token: TOKENS.USDC,
    tokenLogo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    collateral: TOKENS.FTM,
    collateralLogo:
      "https://s2.coinmarketcap.com/static/img/coins/64x64/3513.png",
    collateralPrice: 0.31,
    tokenPrice: 1,
    apr: 1,
    ltv: 75,
    oracle: "Chainlink",
    borrowed: 0,
    available: 5145,
  },
  {
    token: TOKENS.USDC,
    tokenLogo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    collateral: TOKENS.MATIC,
    collateralLogo:
      "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    collateralPrice: 0.851,
    tokenPrice: 1,
    apr: 1,
    ltv: 75,
    oracle: "Chainlink",
    borrowed: 0,
    available: 1003,
  },
  {
    token: TOKENS.USDC,
    tokenLogo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    collateral: TOKENS.OP,
    collateralLogo:
      "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
    collateralPrice: 0.79,
    tokenPrice: 1,
    apr: 1,
    ltv: 75,
    oracle: "Chainlink",
    strategy: "None",
    borrowed: 0,
    available: 0,
  },
  {
    token: TOKENS.USDC,
    tokenLogo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    collateral: TOKENS.AVAX,
    collateralLogo:
      "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
    collateralPrice: 23.66,
    tokenPrice: 1,
    apr: 1,
    ltv: 75,
    oracle: "Chainlink",
    strategy: "None",
    borrowed: 0,
    available: 0,
  },
];

export const FURUCOMBO_CUBES = [
  Furucombo,
  Uniswapv2,
  Aave,
  Sushiswap,
  Curve,
  Yearn,
  Compound,
  Maker,
  // OneInch,
  // Paraswap,
  // UniswapV3,
  Bprotocol,
  Synthetix,
  Utility,
];
