import { TOKENS_SYMBOLS } from "./tokens";
import {
  Furucombo,
  Uniswapv2,
  Aave,
  Sushiswap,
  Curve,
  Yearn,
  Compound,
  Maker,
  // OneInch,
  // Paraswap,
  // UniswapV3,
  Bprotocol,
  Synthetix,
  Utility,
} from "./furucomboConfig";

const TOKENS = TOKENS_SYMBOLS;

export const PAIR_LIST = [
  {
    token: TOKENS.WETH,
    collateral: TOKENS.USDC,
    tokenPrice: 1121.08,
    liquidation: 0.750756387059963,
    health: 0.117984,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 5882,
    available: 7855,
  },
  {
    token: TOKENS.DAI,
    collateral: TOKENS.WETH,
    tokenPrice: 1,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 2437,
    available: 292450,
  },
  {
    token: TOKENS.DAI,
    collateral: TOKENS.USDC,
    tokenPrice: 1,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 0.001008,
  },
];

export const BORROW_PAIR_LIST = [
  {
    token: TOKENS.WETH,
    collateral: TOKENS.USDC,
    tokenPrice: 1121.08,
    liquidation: 0.750756387059963,
    health: 0.117984,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 5882,
    available: 7855,
  },
  {
    token: TOKENS.USDC,
    collateral: TOKENS.ETH,
    tokenPrice: 1,
    liquidation: 1.33189,
    health: 0.119723,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 5777,
    available: 6693,
  },
  {
    token: TOKENS.USDC,
    collateral: TOKENS.DAI,
    tokenPrice: 1,
    liquidation: 0.609654,
    health: 0,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 0.001009,
  },
  {
    token: TOKENS.USDC,
    collateral: TOKENS.FRAX,
    tokenPrice: 1,
    liquidation: 1,
    health: 1,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 0,
  },
  {
    token: TOKENS.DAI,
    collateral: TOKENS.ETH,
    tokenPrice: 20245.07,
    liquidation: 1.33185,
    health: 0.120176,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 2745,
    available: 6119,
  },
  {
    token: TOKENS.DAI,
    collateral: TOKENS.USDC,
    tokenPrice: 1,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 0.001008,
  },
  {
    token: TOKENS.ETH,
    collateral: TOKENS.USDC,
    tokenPrice: 1121.08,
    liquidation: 0.750815,
    health: 0.119723,
    apr: 0.25,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 5777,
    available: 6693,
  },
  {
    token: TOKENS.ETH,
    collateral: TOKENS.DAI,
    tokenPrice: 1121.08,
    liquidation: 0.00120175,
    health: 147931,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 1,
  },
  {
    token: TOKENS.ETH,
    collateral: TOKENS.FRAX,
    tokenPrice: 1121.08,
    liquidation: 0.750859,
    health: 0.120688,
    apr: 1,
    oracle: "Chainlink",
    strategy: "Active",
    ltv: 75,
    borrowed: 0,
    available: 0,
  },
];

export const FURUCOMBO_CUBES = [
  Furucombo,
  Uniswapv2,
  Aave,
  Sushiswap,
  Curve,
  Yearn,
  Compound,
  Maker,
  // OneInch,
  // Paraswap,
  // UniswapV3,
  Bprotocol,
  Synthetix,
  Utility,
];
